### ISSUE TITLE
Seeing AttributeError: 'SubRequest' object has no attribute 'path' since 1.6

### ISSUE THREAD

**Issue by radiumsurfer** [gabrielcnr/pytest-datadir#89]
Hello,

We're seeing the failure

```
  @pytest.fixture(scope="module")
    def original_datadir(request):
>       return request.path.parent / request.path.stem
E       AttributeError: 'SubRequest' object has no attribute 'path'

../../../venv3/lib64/python3.11/site-packages/pytest_datadir/plugin.py:45: AttributeError
```

since release of 1.6 an hour ago.

is there a version requirement for request? where should it be from?

**Comment by nicoddemus** [comment]
Hi @radiumsurfer,

Sorry about that, seems a regression due to https://github.com/gabrielcnr/pytest-datadir/pull/87.

**Comment by nicoddemus** [comment]
@radiumsurfer which pytest version are you using?

**Comment by radiumsurfer** [comment]
6.2.5

**Comment by nicoddemus** [comment]
Ahh OK, we will need to bump the required pytest version then.

I yanked the `1.6.0` release from PyPI and make a new one. Thanks for the report.
